[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Preserve existing role-based routing
[[redirects]]
  from = "/role/*"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/b/*"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/i/*"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/brands/*"
  to = "/:splat"
  status = 200

# Development settings
[dev]
  command = "npm run dev"
  port = 3000
  publish = "dist"

# This should be the last redirect rule
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200